site_name: Документация Конкрит
site_dir: 'wiki/GENERIC/generic/build'
site_url: https://bountyhanter.github.io/IKT2/
repo_name: Репозитории разработчика
repo_url: https://github.com/BountyHanter

nav:
  - 'Описание файлов кода':
    - bot.py: code-fiels/bot-py.md
    - Пояснение про обработчик событий: Event_Handler.md
    - Создание бота в телеграм: tg_bot.md



#theme: readthedocs
theme:
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - header.autohide
    - navigation.indexes
  name: material
  logo: assets/book.svg
  palette:
    scheme: slate
    primary: yellow
    accent: red
  icon:
    repo: fontawesome/brands/github



dev_addr:
  127.0.0.1:8200


  #markdown_extensions:
    #- toc:
        #permalink: True

markdown_extensions:


  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  #- toc:
      #permalink: True


# сворачивание страниц
# collapse_single_pages: true

plugins:
    - search
    - awesome-pages
    - tags:


site_author:
    Денис Гуляев


#pip
#pip install mkdocs-awesome-pages-plugin
